spring:
 application:
  name: OrderService
 datasource:
  url: jdbc:h2:mem:store
  driver-class-name: org.h2.Driver
  username: sa
  password: janu
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
   ddl-auto: update
server:
  port: 8010
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/

